# Generated by Django 5.1.2 on 2025-11-03 23:15

import core.validators
import django.db.models.deletion
import equipment_management.validators
import geolocation.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_leased', models.BooleanField(default=False)),
                ('lease_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('is_active', models.BooleanField(default=True)),
                ('vin', models.CharField(max_length=17, unique=True, validators=[core.validators.validate_not_whitespace_only, equipment_management.validators.validate_vin])),
                ('license_plate_state_usps_abbreviation', models.CharField(blank=True, max_length=2, null=True, validators=[geolocation.validators.validate_usps_abbreviation])),
                ('license_plate_number', models.CharField(blank=True, max_length=10, null=True)),
                ('weigth_lbs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[core.validators.validate_not_negative])),
                ('length_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[core.validators.validate_not_negative])),
                ('status', models.CharField(choices=[('ON ROAD', 'The trailer is currently on the road'), ('STANDBY', 'The trailer is currently in the yard or on standby')], default='STANDBY', max_length=7)),
                ('type', models.CharField(choices=[('VAN', 'The trailer is a van'), ('DRYVAN', 'The trailer is a dry van'), ('REFEER', 'The trailer is a refeer')], default='VAN', max_length=6)),
                ('assigned_driver', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_driver', to='user_management.driver')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trailers', to='crm.company')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('vin', ''), _negated=True), name='trailer_vin_not_empty'), models.CheckConstraint(condition=models.Q(('weigth_lbs__isnull', False), ('weigth_lbs__lt', 0), _negated=True), name='Trailer_weigth_lbs_is_negative'), models.CheckConstraint(condition=models.Q(('length_ft__isnull', False), ('length_ft__lt', 0), _negated=True), name='Trailer_length_ft_is_negative'), models.CheckConstraint(condition=models.Q(('status__in', ['ON ROAD', 'STANDBY'])), name='trailer_status_choices_violation'), models.CheckConstraint(condition=models.Q(('type__in', ['VAN', 'DRYVAN', 'REFEER'])), name='trailer_type_choices_violation')],
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_leased', models.BooleanField(default=False)),
                ('lease_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('is_active', models.BooleanField(default=True)),
                ('vin', models.CharField(max_length=17, unique=True, validators=[core.validators.validate_not_whitespace_only, equipment_management.validators.validate_vin])),
                ('license_plate_state_usps_abbreviation', models.CharField(blank=True, max_length=2, null=True, validators=[geolocation.validators.validate_usps_abbreviation])),
                ('license_plate_number', models.CharField(blank=True, max_length=10, null=True)),
                ('weigth_lbs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[core.validators.validate_not_negative])),
                ('length_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[core.validators.validate_not_negative])),
                ('status', models.CharField(choices=[('ON ROAD', 'The truck is currently on the road'), ('STANDBY', 'The truck is currently in the yard or on standby')], default='STANDBY', max_length=7)),
                ('assigned_driver', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_truck', to='user_management.driver')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='crm.company')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('vin', ''), _negated=True), name='truck_vin_not_empty'), models.CheckConstraint(condition=models.Q(('weigth_lbs__isnull', False), ('weigth_lbs__lt', 0), _negated=True), name='Truck_weigth_lbs_is_negative'), models.CheckConstraint(condition=models.Q(('length_ft__isnull', False), ('length_ft__lt', 0), _negated=True), name='Truck_length_ft_is_negative'), models.CheckConstraint(condition=models.Q(('status__in', ['ON ROAD', 'STANDBY'])), name='truck_status_choices_violation')],
            },
        ),
    ]
