# Generated by Django 5.1.2 on 2025-11-03 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('equipment_management', '0001_initial'),
        ('geolocation', '0001_initial'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distance_miles', models.FloatField(default=0.0)),
                ('route_link', models.TextField(blank=True, null=True)),
                ('custom_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geolocation.location')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatch.route')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('route', 'order')},
            },
        ),
        migrations.AddField(
            model_name='route',
            name='locations',
            field=models.ManyToManyField(through='dispatch.RouteStop', to='geolocation.location'),
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_hazmat', models.BooleanField(default=False)),
                ('pickup_datetime', models.DateTimeField(blank=True, null=True)),
                ('delivery_datetime', models.DateTimeField(blank=True, null=True)),
                ('assignment_datetime', models.DateTimeField(blank=True, null=True)),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('weigth_lbs', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('WAITING', 'The load is has yet to be delivered'), ('ON ROAD', 'The load is in the process of being delivered'), ('DELIVERED', 'The load has been delivered')], default='WAITING', max_length=9)),
                ('pickup_comment', models.TextField(blank=True, null=True)),
                ('delivery_comment', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='crm.company')),
                ('contracted_company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracted_loads', to='crm.company')),
                ('driver', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='user_management.driver')),
                ('trailer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='equipment_management.trailer')),
                ('truck', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='equipment_management.truck')),
                ('route', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='dispatch.route')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['WAITING', 'ON ROAD', 'DELIVERED'])), name='load_status_choices_violation')],
            },
        ),
    ]
