## NOTE: This entire code was generated by chatgpt so don't trust anything, nothing was tested 
import aiohttp
import asyncio

class AsyncGeocoder:
    def __init__(self, provider="osm", api_key=None, user_agent="my-geocoder"):
        self.provider = provider.lower()
        self.api_key = api_key
        self.user_agent = user_agent

    async def geocode(self, address):
        if self.provider == "google":
            return await self._geocode_google(address)
        elif self.provider == "osm":
            return await self._geocode_osm(address)
        else:
            raise ValueError("Unsupported provider")

    async def reverse_geocode(self, lat, lon):
        if self.provider == "google":
            return await self._reverse_google(lat, lon)
        elif self.provider == "osm":
            return await self._reverse_osm(lat, lon)
        else:
            raise ValueError("Unsupported provider")

    async def _geocode_google(self, address):
        url = "https://maps.googleapis.com/maps/api/geocode/json"
        params = {
            "address": address,
            "key": self.api_key
        }
        async with aiohttp.ClientSession() as session:
            async with session.get(url, params=params) as response:
                data = await response.json()
        if data['status'] != 'OK':
            raise Exception("Google Geocoding Error: " + data['status'])
        location = data['results'][0]['geometry']['location']
        return location['lat'], location['lng']

    async def _reverse_google(self, lat, lon):
        url = "https://maps.googleapis.com/maps/api/geocode/json"
        params = {
            "latlng": f"{lat},{lon}",
            "key": self.api_key
        }
        async with aiohttp.ClientSession() as session:
            async with session.get(url, params=params) as response:
                data = await response.json()
        if data['status'] != 'OK':
            raise Exception("Google Reverse Geocoding Error: " + data['status'])
        return data['results'][0]['formatted_address']

    async def _geocode_osm(self, address):
        url = "https://nominatim.openstreetmap.org/search"
        params = {
            "q": address,
            "format": "json",
            "limit": 1
        }
        headers = {"User-Agent": self.user_agent}
        async with aiohttp.ClientSession(headers=headers) as session:
            async with session.get(url, params=params) as response:
                data = await response.json()
        if not data:
            raise Exception("OSM Geocoding Error: No results found")
        return float(data[0]['lat']), float(data[0]['lon'])

    async def _reverse_osm(self, lat, lon):
        url = "https://nominatim.openstreetmap.org/reverse"
        params = {
            "lat": lat,
            "lon": lon,
            "format": "json"
        }
        headers = {"User-Agent": self.user_agent}
        async with aiohttp.ClientSession(headers=headers) as session:
            async with session.get(url, params=params) as response:
                data = await response.json()
        if 'error' in data:
            raise Exception("OSM Reverse Geocoding Error: " + data['error'])
        return data['display_name']
