# Generated by Django 5.1.2 on 2025-11-03 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatcher',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.userprofile')),
            ],
            bases=('core.userprofile',),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.userprofile')),
            ],
            bases=('core.userprofile',),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.userprofile')),
                ('payment_type', models.CharField(choices=[('$MILE', '$ per mile'), ('%REVE', '% per revenue'), ('$WEEK', 'flat $ per week')], default='$MILE', max_length=5)),
                ('pay_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('is_hazmat_endorsed', models.BooleanField(default=False)),
                ('is_tanker_endorsed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ON ROAD', 'The driver is currently on the road'), ('STANDBY', 'The driver is currently in the yard or on standby')], default='STANDBY', max_length=7)),
                ('assigned_dispatcher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='user_management.dispatcher')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['ON ROAD', 'STANDBY'])), name='driver_status_choices_violation'), models.CheckConstraint(condition=models.Q(('payment_type__in', ['$MILE', '%REVE', '$WEEK'])), name='driver_payment_type_choices_violation')],
            },
            bases=('core.userprofile',),
        ),
    ]
