# Generated by Django 5.1.2 on 2025-11-03 23:15

import core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, validators=[core.validators.validate_not_whitespace_only])),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='companyindustry_name_not_empty')],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, validators=[core.validators.validate_not_whitespace_only])),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='US')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dot_number', models.CharField(blank=True, max_length=7, null=True)),
                ('mc_number', models.CharField(blank=True, max_length=7, null=True)),
                ('website', models.URLField(blank=True, max_length=128, null=True)),
                ('industries', models.ManyToManyField(related_name='companies', to='crm.companyindustry')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='company_name_not_empty')],
            },
        ),
    ]
