"""
Django settings for SmartTruck project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-230rf#_ipev8lekw!0sf3f+_p5c49&xo-47lw29&c2vu&pd!p*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'corsheaders', ## 
    
    'daphne', ## used for creating web sockets during local developement. You must create a docker container for deployment

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    ##django apps
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'django_filters',
    'phonenumber_field',
    'channels',             ## used for creating web sockets/channeling ## https://channels.readthedocs.io/en/latest/

    ## custom apps: 
    ## apps that our project uses
    'crm', ## the business logic for handling customers/leads (employees of different companies)
    'core', ## the core application where all our business logic is located
    'geolocation', ## the goelocations that are used for dispatching
    'user_management', ## the business logic for handling customers/leads (employees of different companies)
    'equipment_management', ## the business logic for handling customers/leads (employees of different companies)
    'dispatch', ## the business logic of dispatching, routing, viewing trucks
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware", ## this must be loaded before django middleware 

    'django.middleware.security.SecurityMiddleware',    
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

## What addresses are allowed to be accessed
CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://localhost:8080",
]

CORS_ORIGIN_WHITELIST = (
    'http://localhost:8080'
)

CORS_ALLOW_HEADERS = [
    'Authorization',
    'Content-Type',
    'X-CSRFToken',
]

CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'DELETE',
    'OPTIONS',
]

ROOT_URLCONF = 'SmartTruck.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SmartTruck.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {   
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "diplomski_db",  # Database name
        "USER": "postgres",  # this is the default username
        "PASSWORD": "ftn",  # 
        "HOST": "localhost",  # 
        "PORT": "5432",  # default port
        # "OPTIONS": {
        #     "pool": True, ## use a connecion pool using 'psycopg' (https://www.psycopg.org/psycopg3/), needs to be installed first
        # }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# Authentication backends
# https://docs.djangoproject.com/en/5.2/topics/auth/customizing/
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend', ## admin page, localhost:8000/admin, regular users that log in via email will go through the next auth backend
    'core.authenticator.AuthBackend',            ## custom auth backend for regular users that log in via email
]


# JWT Authentication settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',  #  makes everything public by default
    ),
    ## you can not set the page size through the settings file
    ## you need to inherit the PageNumberPagination and overwrite the page_size query paramater to 'page_size'
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # 'PAGE_SIZE': 5, ## 25
    # 'MAX_PAGE_SIZE': 100,
    'DEFAULT_PAGINATION_CLASS': 'core.paginations.CustomPageNumberPagination',
}

from datetime import timedelta
SIMPLE_JWT = {
    # 'ACCESS_TOKEN_LIFETIME': timedelta(minutes=120),  # You can change the lifetime
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),  # You can change the lifetime
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
}


## Emailing 

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'stevanovicsrdjan1@gmail.com' ## sorry srdjane but I'm gonna use this one for now
EMAIL_HOST_PASSWORD = 'bglcrrdyjytbkxib'


## Frontend domain
## used when confirming the user email. The confirmation link looks like f`http//{FRONTEND_DOMAIN}/whatever`
## let chatgpt explain this: get_current_site(self.context['request']).domain
FRONTEND_DOMAIN = 'localhost:8080'



## 
ASGI_APPLICATION = "SmartTruck.asgi.application"
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",  # for dev
    },
}