# Generated by Django 5.1.2 on 2025-11-03 23:15

import geolocation.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lat', models.FloatField(blank=True, null=True, validators=[geolocation.validators.validate_lat])),
                ('lng', models.FloatField(blank=True, null=True, validators=[geolocation.validators.validate_lng])),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('lat__isnull', True), ('lng__isnull', True)), models.Q(('lat__isnull', False), ('lng__isnull', False)), _connector='OR'), name='Location_lat_lng_both_or_none'), models.CheckConstraint(condition=models.Q(models.Q(('lat__isnull', False), ('lng__isnull', False)), models.Q(('lat__gt', 90), ('lat__lt', -90), ('lng__gt', 180), ('lng__lt', -180)), _connector='OR'), name='Location_lat_lng_invalid_value')],
            },
        ),
    ]
